// Generated by scripts/build-offices.mjs — do not edit by hand.
//
// Every NWS Weather Forecast Office, grouped by region, from the same reference map
// service build-cwa.mjs takes geometry from. Regenerate with:
//
//   node scripts/build-offices.mjs
//
// An office is `ready` only once the site has the assets to draw it — a map bundle in
// public/offices/, a lattice in public/gridpoints/ and labeled cities in public/cities/.
// That is derived from the files themselves, so this can't claim an office is drawable
// when it isn't. Offices that aren't ready are still listed, so the picker shows the real
// national map rather than pretending the country is four offices wide, but they can't be
// selected. To add one, build its assets:
//
//   build-office-bundles → build-office-gridpoints → build-office-cities → build-offices

export type OfficeId =
  | "AKQ"
  | "ALY"
  | "BGM"
  | "BOX"
  | "BTV"
  | "BUF"
  | "CAE"
  | "CAR"
  | "CHS"
  | "CLE"
  | "CTP"
  | "GSP"
  | "GYX"
  | "ILM"
  | "ILN"
  | "LWX"
  | "MHX"
  | "OKX"
  | "PBZ"
  | "PHI"
  | "RAH"
  | "RLX"
  | "RNK"
  | "ABR"
  | "APX"
  | "ARX"
  | "BIS"
  | "BOU"
  | "CYS"
  | "DDC"
  | "DLH"
  | "DMX"
  | "DTX"
  | "DVN"
  | "EAX"
  | "FGF"
  | "FSD"
  | "GID"
  | "GJT"
  | "GLD"
  | "GRB"
  | "GRR"
  | "ICT"
  | "ILX"
  | "IND"
  | "IWX"
  | "JKL"
  | "LBF"
  | "LMK"
  | "LOT"
  | "LSX"
  | "MKX"
  | "MPX"
  | "MQT"
  | "OAX"
  | "PAH"
  | "PUB"
  | "RIW"
  | "SGF"
  | "TOP"
  | "UNR"
  | "ABQ"
  | "AMA"
  | "BMX"
  | "BRO"
  | "CRP"
  | "EPZ"
  | "EWX"
  | "FFC"
  | "FWD"
  | "HGX"
  | "HUN"
  | "JAN"
  | "JAX"
  | "KEY"
  | "LCH"
  | "LIX"
  | "LUB"
  | "LZK"
  | "MAF"
  | "MEG"
  | "MFL"
  | "MLB"
  | "MOB"
  | "MRX"
  | "OHX"
  | "OUN"
  | "SHV"
  | "SJT"
  | "SJU"
  | "TAE"
  | "TBW"
  | "TSA"
  | "BOI"
  | "BYZ"
  | "EKA"
  | "FGZ"
  | "GGW"
  | "HNX"
  | "LKN"
  | "LOX"
  | "MFR"
  | "MSO"
  | "MTR"
  | "OTX"
  | "PDT"
  | "PIH"
  | "PQR"
  | "PSR"
  | "REV"
  | "SEW"
  | "SGX"
  | "SLC"
  | "STO"
  | "TFX"
  | "TWC"
  | "VEF"
  | "AFC"
  | "AFG"
  | "AJK"
  | "GUM"
  | "HFO"
  | "PPG"
  | "PQE"
  | "PQW"
  | "US";

export type RegionId = "eastern" | "central" | "southern" | "western" | "alaska" | "pacific";

export type Office = {
  id: OfficeId;
  /** The office's own location, as NWS states it. */
  city: string;
  state: string;
  /** How the office is named to readers. */
  label: string;
  /** Whether the site has the assets to draw this office yet. */
  ready?: boolean;
};

export type Region = {
  id: RegionId;
  /** NWS's own shorthand for the region, e.g. ER. */
  short: string;
  name: string;
  /** Where NWS headquarters the region, as it labels it. */
  hq: string;
  offices: Office[];
};

export const REGIONS: Region[] = [
  {
    id: "eastern",
    short: "ER",
    name: "Eastern Region",
    hq: "Bohemia, NY",
    offices: [
      { id: "AKQ", city: "Wakefield", state: "VA", label: "Wakefield", ready: true },
      { id: "ALY", city: "Albany", state: "NY", label: "Albany", ready: true },
      { id: "BGM", city: "Binghamton", state: "NY", label: "Binghamton", ready: true },
      { id: "BOX", city: "Boston/Norton", state: "MA", label: "Boston/Norton", ready: true },
      { id: "BTV", city: "Burlington", state: "VT", label: "Burlington", ready: true },
      { id: "BUF", city: "Buffalo", state: "NY", label: "Buffalo", ready: true },
      { id: "CAE", city: "Columbia", state: "SC", label: "Columbia", ready: true },
      { id: "CAR", city: "Caribou", state: "ME", label: "Caribou", ready: true },
      { id: "CHS", city: "Charleston", state: "SC", label: "Charleston", ready: true },
      { id: "CLE", city: "Cleveland", state: "OH", label: "Cleveland", ready: true },
      { id: "CTP", city: "State College", state: "PA", label: "Central Pennsylvania", ready: true },
      { id: "GSP", city: "Greenville-Spartanburg", state: "SC", label: "Greenville-Spartanburg", ready: true },
      { id: "GYX", city: "Gray", state: "ME", label: "Gray", ready: true },
      { id: "ILM", city: "Wilmington", state: "NC", label: "Wilmington", ready: true },
      { id: "ILN", city: "Wilmington", state: "OH", label: "Wilmington", ready: true },
      { id: "LWX", city: "Baltimore MD/Washington", state: "DC", label: "Baltimore / Washington", ready: true },
      { id: "MHX", city: "Newport/Morehead City", state: "NC", label: "Newport/Morehead City", ready: true },
      { id: "OKX", city: "Upton", state: "NY", label: "New York City", ready: true },
      { id: "PBZ", city: "Pittsburgh", state: "PA", label: "Pittsburgh", ready: true },
      { id: "PHI", city: "Mount Holly", state: "NJ", label: "Philadelphia / Mount Holly", ready: true },
      { id: "RAH", city: "Raleigh", state: "NC", label: "Raleigh", ready: true },
      { id: "RLX", city: "Charleston", state: "WV", label: "Charleston", ready: true },
      { id: "RNK", city: "Blacksburg", state: "VA", label: "Blacksburg", ready: true },
    ],
  },
  {
    id: "central",
    short: "CR",
    name: "Central Region",
    hq: "Kansas City, MO",
    offices: [
      { id: "ABR", city: "Aberdeen", state: "SD", label: "Aberdeen", ready: true },
      { id: "APX", city: "Gaylord", state: "MI", label: "Gaylord", ready: true },
      { id: "ARX", city: "La Crosse", state: "WI", label: "La Crosse", ready: true },
      { id: "BIS", city: "Bismarck", state: "ND", label: "Bismarck", ready: true },
      { id: "BOU", city: "Denver", state: "CO", label: "Denver", ready: true },
      { id: "CYS", city: "Cheyenne", state: "WY", label: "Cheyenne", ready: true },
      { id: "DDC", city: "Dodge City", state: "KS", label: "Dodge City", ready: true },
      { id: "DLH", city: "Duluth", state: "MN", label: "Duluth", ready: true },
      { id: "DMX", city: "Des Moines", state: "IA", label: "Des Moines", ready: true },
      { id: "DTX", city: "Detroit/Pontiac", state: "MI", label: "Detroit/Pontiac", ready: true },
      { id: "DVN", city: "Quad Cities IA", state: "IL", label: "Quad Cities IA", ready: true },
      { id: "EAX", city: "Kansas City/Pleasant Hill", state: "MO", label: "Kansas City/Pleasant Hill", ready: true },
      { id: "FGF", city: "Grand Forks", state: "ND", label: "Grand Forks", ready: true },
      { id: "FSD", city: "Sioux Falls", state: "SD", label: "Sioux Falls", ready: true },
      { id: "GID", city: "Hastings", state: "NE", label: "Hastings", ready: true },
      { id: "GJT", city: "Grand Junction", state: "CO", label: "Grand Junction", ready: true },
      { id: "GLD", city: "Goodland", state: "KS", label: "Goodland", ready: true },
      { id: "GRB", city: "Green Bay", state: "WI", label: "Green Bay", ready: true },
      { id: "GRR", city: "Grand Rapids", state: "MI", label: "Grand Rapids", ready: true },
      { id: "ICT", city: "Wichita", state: "KS", label: "Wichita", ready: true },
      { id: "ILX", city: "Lincoln", state: "IL", label: "Lincoln", ready: true },
      { id: "IND", city: "Indianapolis", state: "IN", label: "Indianapolis", ready: true },
      { id: "IWX", city: "Northern Indiana", state: "IN", label: "Northern Indiana", ready: true },
      { id: "JKL", city: "Jackson", state: "KY", label: "Jackson", ready: true },
      { id: "LBF", city: "North Platte", state: "NE", label: "North Platte", ready: true },
      { id: "LMK", city: "Louisville", state: "KY", label: "Louisville", ready: true },
      { id: "LOT", city: "Chicago", state: "IL", label: "Chicago", ready: true },
      { id: "LSX", city: "St Louis", state: "MO", label: "St Louis", ready: true },
      { id: "MKX", city: "Milwaukee/Sullivan", state: "WI", label: "Milwaukee/Sullivan", ready: true },
      { id: "MPX", city: "Twin Cities/Chanhassen", state: "MN", label: "Twin Cities/Chanhassen", ready: true },
      { id: "MQT", city: "Marquette", state: "MI", label: "Marquette", ready: true },
      { id: "OAX", city: "Omaha/Valley", state: "NE", label: "Omaha/Valley", ready: true },
      { id: "PAH", city: "Paducah", state: "KY", label: "Paducah", ready: true },
      { id: "PUB", city: "Pueblo", state: "CO", label: "Pueblo", ready: true },
      { id: "RIW", city: "Riverton", state: "WY", label: "Riverton", ready: true },
      { id: "SGF", city: "Springfield", state: "MO", label: "Springfield", ready: true },
      { id: "TOP", city: "Topeka", state: "KS", label: "Topeka", ready: true },
      { id: "UNR", city: "Rapid City", state: "SD", label: "Rapid City", ready: true },
    ],
  },
  {
    id: "southern",
    short: "SR",
    name: "Southern Region",
    hq: "Fort Worth, TX",
    offices: [
      { id: "ABQ", city: "Albuquerque", state: "NM", label: "Albuquerque", ready: true },
      { id: "AMA", city: "Amarillo", state: "TX", label: "Amarillo", ready: true },
      { id: "BMX", city: "Birmingham", state: "AL", label: "Birmingham", ready: true },
      { id: "BRO", city: "Brownsville", state: "TX", label: "Brownsville", ready: true },
      { id: "CRP", city: "Corpus Christi", state: "TX", label: "Corpus Christi", ready: true },
      { id: "EPZ", city: "El Paso Tx/Santa Teresa", state: "NM", label: "El Paso Tx/Santa Teresa", ready: true },
      { id: "EWX", city: "Austin/San Antonio", state: "TX", label: "Austin/San Antonio", ready: true },
      { id: "FFC", city: "Peachtree City", state: "GA", label: "Peachtree City", ready: true },
      { id: "FWD", city: "Fort Worth", state: "TX", label: "Fort Worth", ready: true },
      { id: "HGX", city: "Houston/Galveston", state: "TX", label: "Houston/Galveston", ready: true },
      { id: "HUN", city: "Huntsville", state: "AL", label: "Huntsville", ready: true },
      { id: "JAN", city: "Jackson", state: "MS", label: "Jackson", ready: true },
      { id: "JAX", city: "Jacksonville", state: "FL", label: "Jacksonville", ready: true },
      { id: "KEY", city: "Key West", state: "FL", label: "Key West", ready: true },
      { id: "LCH", city: "Lake Charles", state: "LA", label: "Lake Charles", ready: true },
      { id: "LIX", city: "New Orleans", state: "LA", label: "New Orleans", ready: true },
      { id: "LUB", city: "Lubbock", state: "TX", label: "Lubbock", ready: true },
      { id: "LZK", city: "Little Rock", state: "AR", label: "Little Rock", ready: true },
      { id: "MAF", city: "Midland/Odessa", state: "TX", label: "Midland/Odessa", ready: true },
      { id: "MEG", city: "Memphis", state: "TN", label: "Memphis", ready: true },
      { id: "MFL", city: "Miami", state: "FL", label: "Miami", ready: true },
      { id: "MLB", city: "Melbourne", state: "FL", label: "Melbourne", ready: true },
      { id: "MOB", city: "Mobile", state: "AL", label: "Mobile", ready: true },
      { id: "MRX", city: "Morristown", state: "TN", label: "Morristown", ready: true },
      { id: "OHX", city: "Nashville", state: "TN", label: "Nashville", ready: true },
      { id: "OUN", city: "Norman", state: "OK", label: "Norman", ready: true },
      { id: "SHV", city: "Shreveport", state: "LA", label: "Shreveport", ready: true },
      { id: "SJT", city: "San Angelo", state: "TX", label: "San Angelo", ready: true },
      { id: "SJU", city: "San Juan", state: "PR", label: "San Juan", ready: true },
      { id: "TAE", city: "Tallahassee", state: "FL", label: "Tallahassee", ready: true },
      { id: "TBW", city: "Tampa Bay Ruskin", state: "FL", label: "Tampa Bay Ruskin", ready: true },
      { id: "TSA", city: "Tulsa", state: "OK", label: "Tulsa", ready: true },
    ],
  },
  {
    id: "western",
    short: "WR",
    name: "Western Region",
    hq: "Salt Lake City, UT",
    offices: [
      { id: "BOI", city: "Boise", state: "ID", label: "Boise", ready: true },
      { id: "BYZ", city: "Billings", state: "MT", label: "Billings", ready: true },
      { id: "EKA", city: "Eureka", state: "CA", label: "Eureka", ready: true },
      { id: "FGZ", city: "Flagstaff", state: "AZ", label: "Flagstaff", ready: true },
      { id: "GGW", city: "Glasgow", state: "MT", label: "Glasgow", ready: true },
      { id: "HNX", city: "Hanford", state: "CA", label: "Hanford", ready: true },
      { id: "LKN", city: "Elko", state: "NV", label: "Elko", ready: true },
      { id: "LOX", city: "Los Angeles/Oxnard", state: "CA", label: "Los Angeles/Oxnard", ready: true },
      { id: "MFR", city: "Medford", state: "OR", label: "Medford", ready: true },
      { id: "MSO", city: "Missoula", state: "MT", label: "Missoula", ready: true },
      { id: "MTR", city: "San Francisco", state: "CA", label: "San Francisco", ready: true },
      { id: "OTX", city: "Spokane", state: "WA", label: "Spokane", ready: true },
      { id: "PDT", city: "Pendleton", state: "OR", label: "Pendleton", ready: true },
      { id: "PIH", city: "Pocatello", state: "ID", label: "Pocatello", ready: true },
      { id: "PQR", city: "Portland", state: "OR", label: "Portland", ready: true },
      { id: "PSR", city: "Phoenix", state: "AZ", label: "Phoenix", ready: true },
      { id: "REV", city: "Reno", state: "NV", label: "Reno", ready: true },
      { id: "SEW", city: "Seattle", state: "WA", label: "Seattle", ready: true },
      { id: "SGX", city: "San Diego", state: "CA", label: "San Diego", ready: true },
      { id: "SLC", city: "Salt Lake City", state: "UT", label: "Salt Lake City", ready: true },
      { id: "STO", city: "Sacramento", state: "CA", label: "Sacramento", ready: true },
      { id: "TFX", city: "Great Falls", state: "MT", label: "Great Falls", ready: true },
      { id: "TWC", city: "Tucson", state: "AZ", label: "Tucson", ready: true },
      { id: "VEF", city: "Las Vegas", state: "NV", label: "Las Vegas", ready: true },
    ],
  },
  {
    id: "alaska",
    short: "AR",
    name: "Alaska Region",
    hq: "Anchorage, AK",
    offices: [
      { id: "AFC", city: "Anchorage", state: "AK", label: "Anchorage", ready: true },
      { id: "AFG", city: "Fairbanks", state: "AK", label: "Fairbanks", ready: true },
      { id: "AJK", city: "Juneau", state: "AK", label: "Juneau", ready: true },
    ],
  },
  {
    id: "pacific",
    short: "PR",
    name: "Pacific Region",
    hq: "Honolulu, HI",
    offices: [
      { id: "GUM", city: "Tiyan", state: "GU", label: "Tiyan" },
      { id: "HFO", city: "Honolulu", state: "HI", label: "Honolulu", ready: true },
      { id: "PPG", city: "Pago Pago", state: "AS", label: "Pago Pago" },
      { id: "PQE", city: "Micronesia Domain East", state: "PQ", label: "Micronesia Domain East" },
      { id: "PQW", city: "Micronesia Domain West", state: "PQ", label: "Micronesia Domain West" },
    ],
  },
];

/** The national view, which sits above the regions rather than inside one. */
export const NATIONAL: Office = {"id":"US","city":"United States","state":"US","label":"National","ready":true};

export const OFFICES: Office[] = [...REGIONS.flatMap((region) => region.offices), NATIONAL];
export const OFFICE_IDS: OfficeId[] = OFFICES.map((office) => office.id);
/** The offices the site can actually draw today. */
export const READY_OFFICES: Office[] = OFFICES.filter((office) => office.ready);
export const DEFAULT_OFFICE: OfficeId = "PHI";

export function isOfficeId(value: string | null | undefined): value is OfficeId {
  return typeof value === "string" && (OFFICE_IDS as string[]).includes(value);
}

/**
 * Unknown ids fall back to the default office rather than erroring — and so do offices
 * that exist but have no assets yet, because rendering one would draw another office's
 * boundary rather than fail visibly.
 */
export function findOffice(value: string | null | undefined): Office {
  const office = isOfficeId(value) ? OFFICES.find((entry) => entry.id === value) : undefined;
  if (office?.ready) return office;
  return OFFICES.find((entry) => entry.id === DEFAULT_OFFICE)!;
}

export function findRegion(id: string | null | undefined) {
  return REGIONS.find((region) => region.id === id) ?? null;
}

/** The region that forecasts a given office, for opening the picker where you are. */
export function regionOf(office: OfficeId) {
  return REGIONS.find((region) => region.offices.some((entry) => entry.id === office)) ?? REGIONS[0];
}

/** The national view spans every region, so it is never "in" one. */
export function isNational(office: OfficeId) {
  return office === NATIONAL.id;
}
